function bootstrap(){var O='',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',gb='"><\/script>',X='#',Qb='.cache.html',Z='/',jb='//',Pb=':',nb='::',$b='<script defer="defer">bootstrap.onInjectionDone(\'bootstrap\')<\/script>',fb='<script id="',qb='=',Y='?',sb='Bad handler "',Zb='DOMContentLoaded',Ob="GWT module 'bootstrap' may need to be (re)compiled",hb='SCRIPT',eb='__gwt_marker_bootstrap',ib='base',ab='baseUrl',R='begin',P='bootstrap',cb='bootstrap.nocache.js',mb='bootstrap::',_='clear.cache.gif',pb='content',Rb='css/bootstrap.min.css',Yb='css/font-awesome.min.css',Xb='css/gwt-bootstrap.css',W='end',Ib='gecko',Jb='gecko1_8',S='gwt.codesvr=',T='gwt.hosted=',U='gwt.hybrid',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',Wb='head',Mb='hosted.html?bootstrap',Vb='href',Hb='ie6',Gb='ie8',Fb='ie9',wb='iframe',$='img',xb="javascript:''",Sb='link',Lb='loadExternalRefs',kb='meta',zb='moduleRequested',V='moduleStartup',Eb='msie',lb='name',Bb='opera',yb='position:absolute;width:0;height:0;border:none',Tb='rel',Db='safari',bb='script',Nb='selectingPermutation',Q='startup',Ub='stylesheet',db='undefined',Kb='unknown',Ab='user.agent',Cb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=O,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:P,sessionId:p,subSystem:Q,evtGroup:P,millis:(new Date).getTime(),type:R});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(S)!=-1||(c.indexOf(T)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(U)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(P);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return G(a)}}bootstrap=null;c.gwtOnLoad(z,P,t,y);o&&o({moduleName:P,sessionId:p,subSystem:Q,evtGroup:V,millis:(new Date).getTime(),type:W})}}
function D(){function e(a){var b=a.lastIndexOf(X);if(b==-1){b=a.length}var c=a.indexOf(Y);if(c==-1){c=a.length}var d=a.lastIndexOf(Z,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement($);b.src=a+_;a=e(b.src)}return a}
function g(){var a=F(ab);if(a!=null){return a}return O}
function h(){var a=n.getElementsByTagName(bb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(cb)!=-1){return e(a[b].src)}}return O}
function i(){var a;if(typeof isBodyLoaded==db||!isBodyLoaded()){var b=eb;var c;n.write(fb+b+gb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=hb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return O}
function j(){var a=n.getElementsByTagName(ib);if(a.length>0){return a[a.length-1].href}return O}
function k(){var a=n.location;return a.href==a.protocol+jb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==O){l=h()}if(l==O){l=i()}if(l==O){l=j()}if(l==O&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,O);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}u[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{A=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=n.createElement(wb);a.src=xb;a.id=P;a.style.cssText=yb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:P,sessionId:p,subSystem:Q,evtGroup:V,millis:(new Date).getTime(),type:zb});a.contentWindow.location.replace(t+K)}}
w[Ab]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Bb)!=-1}())return Bb;if(function(){return b.indexOf(Cb)!=-1}())return Db;if(function(){return b.indexOf(Eb)!=-1&&n.documentMode>=9}())return Fb;if(function(){return b.indexOf(Eb)!=-1&&n.documentMode>=8}())return Gb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Hb;if(function(){return b.indexOf(Ib)!=-1}())return Jb;return Kb};v[Ab]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};bootstrap.onScriptLoad=function(){if(H){r=true;C()}};bootstrap.onInjectionDone=function(){q=true;o&&o({moduleName:P,sessionId:p,subSystem:Q,evtGroup:Lb,millis:(new Date).getTime(),type:W});C()};E();D();var J;var K;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(P))){m.location.reload();return}K=Mb;J=O}o&&o({moduleName:P,sessionId:p,subSystem:Q,evtGroup:P,millis:(new Date).getTime(),type:Nb});if(!B()){try{alert(Ob);return;var L=J.indexOf(Pb);if(L!=-1){y=Number(J.substring(L+1));J=J.substring(0,L)}K=J+Qb}catch(a){return}}var M;function N(){if(!s){s=true;if(!__gwt_stylesLoaded[Rb]){var a=n.createElement(Sb);__gwt_stylesLoaded[Rb]=a;a.setAttribute(Tb,Ub);a.setAttribute(Vb,t+Rb);n.getElementsByTagName(Wb)[0].appendChild(a)}if(!__gwt_stylesLoaded[Xb]){var a=n.createElement(Sb);__gwt_stylesLoaded[Xb]=a;a.setAttribute(Tb,Ub);a.setAttribute(Vb,t+Xb);n.getElementsByTagName(Wb)[0].appendChild(a)}if(!__gwt_stylesLoaded[Yb]){var a=n.createElement(Sb);__gwt_stylesLoaded[Yb]=a;a.setAttribute(Tb,Ub);a.setAttribute(Vb,t+Yb);n.getElementsByTagName(Wb)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(Zb,N,false)}if(M){clearInterval(M)}}}
if(n.addEventListener){n.addEventListener(Zb,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(n.readyState)){I();N()}},50);o&&o({moduleName:P,sessionId:p,subSystem:Q,evtGroup:P,millis:(new Date).getTime(),type:W});o&&o({moduleName:P,sessionId:p,subSystem:Q,evtGroup:Lb,millis:(new Date).getTime(),type:R});n.write($b)}
bootstrap();